### ISSUE TITLE
bug ITEM_UPGRADE_MASTER_UPDATE

### ISSUE THREAD

**Issue by Addonman** [alarofrunetotem/ItemLevelDisplay#5]
First i thought its ace error ,but they say its itemleveldisplay error 

https://www.wowace.com/projects/ace3/issues/583

Message: ..\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua line 33:
Attempt to register unknown event "ITEM_UPGRADE_MASTER_UPDATE"
Debug:
[string "=(tail call)"]: ?
[string "=[C]"]: RegisterEvent()
[string "@Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:33: OnUsed()
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:142: RegisterEvent()
[string "@ItemLevelDisplay\ItemLevelDisplay.lua"]:727: OnInitialized()
[string "@ItemLevelDisplay\libs\LibInit\LibInit.lua"]:996:
...ace\AddOns\ItemLevelDisplay\libs\LibInit\LibInit.lua:944
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70:
Ace3\AceAddon-3.0\AceAddon-3.0.lua:65
[string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:498: InitializeAddon()
[string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:623:
Ace3\AceAddon-3.0\AceAddon-3.0.lua:615

**Comment by raysmith59** [comment]
Confirmed, disabling ILD removes the error.

**Comment by raysmith59** [comment]
In very limited testing simply commenting out line 727 in ItemLevelDisplay.LUA (preface it by --) removes the error and ILD still seems to be working, including displaying update details for applicable gear.  I couldn't find a replacement for the ITEM_UPGRADE_MASTER_UPDATE event which got me thinking that maybe there isn't one...

**Comment by Addonman** [comment]
Look they removed stuff like 

GetItemUpdateLevel
GetItemUpgradeItemInfo
GetItemUpgradeStats

and replaced it with 

C_Item.GetCurrentItemTransmogInfo
C_ItemUpgrade.ClearItemUpgrade
C_ItemUpgrade.CloseItemUpgrade
C_ItemUpgrade.GetItemUpgradeCurrentLevel
C_ItemUpgrade.GetItemUpgradeItemInfo
C_ItemUpgrade.GetItemUpgradePvpItemLevelDeltaValues
C_ItemUpgrade.SetItemUpgradeFromCursorItem
C_ItemUpgrade.SetItemUpgradeFromLocation
C_ItemUpgrade.UpgradeItem

how that effects this addon i cant say. 
Choping of something from addon isnt fix  since  i am not sure what features are you choping off with it.

**Comment by zalidthebur** [comment]
@raysmith59  Thanks. That's gotten rid of the error without any impact on the addon I can find.

@Addonman ITEM_UPGRADE_MASTER_UPDATE looks like it's to do with upgrading items via the NPCs. Like the covenant upgrade vendor or the Korthia research vendor. I checked the Night Fae upgrade vendor and all looks okay there. So I have no idea what this actually does. Maybe it's been removed and is now part of the game ? I'm happy to comment out that line until a proper fix is implemented. Each to their own ;-)

**Comment by Adrenaliin** [comment]
@raysmith59 Thanks. I can concur as well - it works and it doesn't seem to reduce functionality (at least visibly)! :)
